CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(50) NOT NULL UNIQUE,
    lastName VARCHAR(50) NOT NULL UNIQUE,
    userPassword VARCHAR(255) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    dateJoined DATETIME DEFAULT CURRENT_TIMESTAMP
);